### ISSUE TITLE
Commit Function Not Returning Proper Value

### ISSUE THREAD

**Issue by nkndy** [vadym-vorobel/bright-local-api#1]
Hi,

I have been using this wrapper to interface with the brightlocal api. Works great except I think I found an error:

, {
    key: 'commit',
    value: function commit(batchId) {
      var _this2 = this;
      console.log('inside', batchId);
      return new _promisePolyfill2.default(function (resolve) {
        _this2.api.put('/v4/batch', { 'batch-id': batchId }).then(function (response) {
          return resolve(response.status);
        }).catch(function (error) {
          throw new Error('Error while committing the batch: ' + error);
        });
      });
    }

I think the return should be:
return resolve(response.success);
according to the documentation here: https://apidocs.brightlocal.com/#commit-batch

If you are able to update this that would be awesome!

**Comment by vadym-vorobel** [comment]
Hi @nkndy. I haven't work with this package for years and even surprised that it still works :)
I've taken a look into the documentation you sent and it seems that your issue makes sense.
Did you try to fix this issue locally? Is it solves your issue? If yes, I'll make changes in the package asap
Thanks!

**Comment by nkndy** [comment]
Thanks for the response @vadym-vorobel,

I have tested on my local. Updated lines 60, 77 & 78 to use the current endpoint for 'getResults' and expose the whole response object for debugging on both function calls. 

, {
    key: 'commit',
    value: function commit(batchId) {
      var _this2 = this;
      return new _promisePolyfill2.default(function (resolve) {
        _this2.api.put('/v4/batch', { 'batch-id': batchId }).then(function (response) {
          return resolve(**response**);
        }).catch(function (error) {
          throw new Error('Error while commiting the batch: ' + error);
        });
      });
    }
------------&&----------
  }, {
    key: 'getResults',
    value: function getResults(batchId) {
      var _this3 = this;
      return new _promisePolyfill2.default(function (resolve) {
        _this3.api.get(**'/v4/batch**', { 'batch-id': batchId }).then(function (response) {
          return resolve(**response**);
        }).catch(function (error) {
          throw new Error('Error while getting result from the batch: ' + error);
        });
      });
    }

**Comment by vadym-vorobel** [comment]
@nkndy thanks for your help. Fixed and published the new version to npm
