### ISSUE TITLE
INVALID_BATCH_ID: 'Batch ID not found'

### ISSUE THREAD

**Issue by MiscociLucaLaurentiu** [vadym-vorobel/bright-local-api#5]
I am getting this error when trying to create a batch.
{ success: false, errors: { INVALID_BATCH_ID: 'Batch ID not found' } }

**Comment by vadym-vorobel** [comment]
Hi @MiscociLucaLaurentiu!
May you give me more information about the issue?
Also, please check that you are using a correct batch ID for your requests.

**Comment by MiscociLucaLaurentiu** [comment]
hy @vadym-vorobel sorry for late response.I did this
![vs code](https://user-images.githubusercontent.com/62329161/93771413-22249100-fc26-11ea-8bd2-7938e2637e39.png)
and get this error in the log { INVALID_BATCH_ID: 'Batch ID not found' } }

**Comment by MiscociLucaLaurentiu** [comment]
i tried also with postman to be sure the batch is created

**Comment by MiscociLucaLaurentiu** [comment]
![git](https://user-images.githubusercontent.com/62329161/93771708-8c3d3600-fc26-11ea-9e9e-d973101dfd50.png)
![git postman 2](https://user-images.githubusercontent.com/62329161/93771738-9101ea00-fc26-11ea-9d5b-17d16480fe3c.png)

**Comment by MiscociLucaLaurentiu** [comment]
it seems that for now you can not add Jobs to a batch,be cause it doesnt find it although it is created.If you encountered this problem,i wait for your response.Thanks in advance.Cheers!

**Comment by vadym-vorobel** [comment]
@MiscociLucaLaurentiu what if you are trying to create a new batch from Postman? Is batch creating in that case?

**Comment by MiscociLucaLaurentiu** [comment]
yes it succesfully,creates the batch from code AND from postman,the problem is on the api call : /v4/ld/fetch-reviews-by-business-data

**Comment by vadym-vorobel** [comment]
@MiscociLucaLaurentiu I'm not sure, but maybe the problem is here:

![image](https://user-images.githubusercontent.com/13135292/93775243-d6c0b180-fc2a-11ea-844b-8c4016aed863.png)

You are using `Ireland` as a value for the country parameter. But BrightLocal accept `USA` value only

**Comment by MiscociLucaLaurentiu** [comment]
i tried the other one
![image](https://user-images.githubusercontent.com/62329161/93776979-dcb79200-fc2c-11ea-8b5c-7d6059b808c1.png)
and still not working

**Comment by MiscociLucaLaurentiu** [comment]
this one does not require only Country USA

**Comment by vadym-vorobel** [comment]
@MiscociLucaLaurentiu I think that this is not an issue of this package. It's just a JS wrapper for the API.
So, if you are getting `BATCH_ID not found` error with Postman too - it's an issue in the initial BrightLocal REST API or in your request.
I think that you can try to create a batch with the USA as a country (if it's possible) and test reviews fetching once more with Postman.

**Comment by MiscociLucaLaurentiu** [comment]
i tried also creating a batch with the USA as a country,still doesn't work, but as you said i guess is an issue with their API.I reported the issue to them.Thanks anyway!

**Comment by vadym-vorobel** [comment]
@MiscociLucaLaurentiu you are welcome!
